apiVersion: v1
kind: ConfigMap
metadata:
  name: marvin-config
  namespace: iaas-marvin
data:
  users.properties: |-
    [users]
    storage=vpatil3,haiyji,garywils,bkota,gmada,vakatta,vkundurt,yingjisu,arvinsi3,joedanfo,tocao,festeban,plockhar
    compute=nitreddy,cdiloren,egorelic,matdavid,papersal,ksheets
    customer=xuqyuan,mollys,ksheik
    firewall=akbansal,cmcelhin,brklaers,kanhamil,stevidav,gstyx,nehaja,sopuliu
---
apiVersion: v1
kind: Pod
metadata:
  name: marvin-app-standalone
  namespace: iaas-marvin
spec:
  containers:
  - image: registry-qa.webex.com/marvin:test3
    imagePullPolicy: IfNotPresent
    name: marvin-app-standalone
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-sm9nq
      readOnly: true
    - name: marvin-config
      mountPath: /opt/wibot/
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-sm9nq
    secret:
      defaultMode: 420
      secretName: default-token-sm9nq
  - name: marvin-config
    configMap:
      name: marvin-config